# Generated by Django 6.0.5 on 2026-09-19 06:35

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_rename_telegram_to_vk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrecord',
            name='period_month',
            field=models.PositiveIntegerField(default=crm.models.current_month, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='period_year',
            field=models.PositiveIntegerField(default=crm.models.current_year, verbose_name='Год'),
        ),
    ]
